version: '3.4'
services:
        coreimagetest:
                build:
                        context: workshop_docker_compose
                container_name: coreimagetest
                ports:
                        - "82:80"
                restart: always


